Makefile
README.md
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
manifest_template.yml
proxies/sandbox/apiproxy/policies/FlowCallout.ApplyRateLimiting.xml
proxies/sandbox/apiproxy/policies/Javascript.AddClientRPDetailsHeader.xml
proxies/sandbox/apiproxy/policies/Javascript.AddConnectionMetadataHeader.xml
proxies/sandbox/apiproxy/policies/javascript.WritePathToVariable.xml
proxies/sandbox/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/resources/jsc/ClientRPDetailsHeader.SetRequestHeaders.js
proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
proxies/sandbox/apiproxy/resources/jsc/WritePathToVariable.js
proxies/sandbox/apiproxy/targets/sandbox.xml
pytest.ini
tests/common_tests.py
tests/sandbox_smoke_tests.py
tests/smoke_tests.py

[NRLF-187] Sandbox deployment

---

azure/azure-release-pipeline.yml

[NRLF-119] Patch release pipeline

---

proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js

[NRLF-277] Update Sandbox Org Pointer Types

---

Makefile
proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
proxies/live/apiproxy/resources/jsc/WritePathToVariable.js
proxies/live/apiproxy/targets/target.xml
proxies/sandbox/apiproxy/resources/jsc/WritePathToVariable.js
proxies/sandbox/apiproxy/targets/sandbox.xml

[NRLF-253] Use Domain Names

---

azure/azure-release-pipeline.yml
manifest_template.yml

[NRLF-274] Enable INT APIGEE Proxy

---

azure/azure-release-pipeline.yml
manifest_template.yml

[NRLF-253] Enable all Non-Prod environments

---

manifest_template.yml

[NRLF-273] Added prod environment to manifest_template.yml

---

azure/azure-release-pipeline.yml

[NRLF-273] Added prod to azure-release-pipeline.yml

---

azure/azure-release-pipeline.yml

[NRLF-273] Removed smoke tests for prod in azure-release-pipeline.yml

---

manifest_template.yml

[NRLF-273] Added ratelimit and quota to prod environment

---

Makefile
azure/templates/run-smoke-tests.yml
tests/sandbox_smoke_tests.py
tests/smoke_tests.py

[NRLF-273] Added APIGEE_APP_ID to smoke tests and set subject to subject.identifier

---

Makefile

[NRLF-273] Remove proxy-name and api-name args for int and prod in Makefile

---

Makefile

[NRLF-273] Re-add api-name and proxy-name args in Makefile for prod envs

---

specification/nrl-consumer-api.yaml

[NRLF-348] Reduce OAS Complexity

---

specification/nrl-consumer-api.yaml

[NRLF-351] OAS Feedback

---

specification/nrl-consumer-api.yaml

[NRLF-351] OAS improvements

---

tests/sandbox_smoke_tests.py
tests/smoke_tests.py

[NRLF-362] Disabled inconsistent tests

---

specification/nrl-consumer-api.yaml

[NRLF-351] OAS updates

---

.gitignore
openapitools.json
specification/nrl-consumer-api.yaml

[NRLF-352] Header Fixes (BUG)

---

proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
specification/nrl-consumer-api.yaml
tests/smoke_tests.py

[NRLF-351] OAS Feedback (Rebased)

---

proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
specification/nrl-consumer-api.yaml

[NRLF-372] OAS iteration

---

proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
proxies/live/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
proxies/sandbox/apiproxy/policies/AssignMessage.AddSandboxAuthorization.xml
proxies/sandbox/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/targets/sandbox.xml
specification/nrl-consumer-api.yaml

Amendments to CORS for all proxies and Authentication for Sandbox.

[NRLF-186] Try our API compatibility

---

azure/azure-release-pipeline.yml

[NRLF-374] depends_on changes for prod

---

specification/nrl-consumer-api.yaml

[NRLF-402] OAS Feedback (Laura)

---

manifest_template.yml

[NRLF-422] configure rate limiting

---

proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js

[NRLF-284] Change separator to whitespace for nrlPointerTypes

---

specification/nrl-consumer-api.yaml

[NRLF-414] Updated nrl-consumer-api.yml

---

specification/nrl-consumer-api.yaml

[NRLF-414] OAS feedback

---

README.md
azure/project.yml
package.json
postman/national_record_locator_consumer_sandbox.json
specification/record-locator/consumer.yaml

[NRLF-399] update apigee paths

---

specification/record-locator/consumer.yaml

Release 2023-04-06

---

specification/record-locator/consumer.yaml

[NRLF-437] tweak description of x-ids

---

specification/record-locator/consumer.yaml

[NRLF-461] Swagger regen for NRLF-461

---

proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js

[NRLF-425]Set NHSD-End-User-Organisation for live proxy

---

proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js

[NRLF-479] Revert the splitting of nrl pointers in sandbox

---

specification/record-locator/consumer.yaml

[NRLF-425] Renamed RequestHeaderReceiverCode to RequestHeaderOrganisationExtensionCode

---

specification/record-locator/consumer.yaml

[NRLF-522] Added Errors section consumer.yaml

---

specification/record-locator/consumer.yaml

[NRLF-522] Bullet points on errors

---

specification/record-locator/consumer.yaml

[NRLF-640] Update consumer.yaml

---

proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js

Added authorization logic to Connectionmetadata

[NRLF-658] enable-s3-auth

---

specification/record-locator/consumer.yaml

[NRLF-585] live urls to narrative

---

specification/record-locator/consumer.yaml

[NRLF-663] Add Open Source Narrative

---

proxies/live/apiproxy/policies/AssignMessage.Errors.CatchAllMessage.xml
proxies/live/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/proxies/default.xml

[NRLF-582] cors issues in try section

---

specification/record-locator/consumer.yaml

[SPINECLI-1190] Add link to postman collection in narrative

---

pyproject.toml

[SPINECLI-1795] Fix azure pipelines requires pyproject

---

specification/record-locator/consumer.yaml

[NRLF-526] Updated CIS2 narrative

---

specification/record-locator/consumer.yaml

updated the supported pointer types as per [SPINECLI-1616](https://nhsd-jira.digital.nhs.uk/browse/SPINECLI-1616) for the consumer API

[SPINECLI-1616] Updated with new snomed codes

---

specification/record-locator/consumer.yaml

[SPINECLI-166](https://nhsd-jira.digital.nhs.uk/browse/SPINECLI-1666) - corrected FHIR document reference link

updated the FHIR Doc url to the correct R4 link

---

specification/record-locator/consumer.yaml

Update `in beta` to `in development`

NRL-687 Update to nrlf release v3.0.2

---

proxies/live/apiproxy/policies/RaiseFault.400MissingODSHeader.xml
proxies/sandbox/apiproxy/policies/RaiseFault.400MissingODSHeader.xml

[NRL-602] Fix typo in 400 error messages

---

specification/record-locator/consumer.yaml

[NRL-670] Add ASID to context.related in spec examples

---

proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js

fix if lookup is false bug

---

proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js

NRL-759 add new i dfor nrl perms

---

proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js

[NRL-855] Add app-id to sandbox proxy headers

---

specification/record-locator/consumer.yaml

NRL-820: Add new pointer types to docs

---

specification/record-locator/consumer.yaml

NRL-1028 Update service level to gold

---

specification/record-locator/consumer.yaml

[NRL-959] Add new pointer types for summary record and pcp

---

proxies/live/apiproxy/policies/RaiseFault.403MissingNRLAppID.xml
proxies/live/apiproxy/proxies/default.xml
proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
proxies/live/apiproxy/targets/target.xml

NRL-818 raise fault for missing nrl app ID

---

proxies/live/apiproxy/policies/RaiseFault.403MissingNRLAppID.xml

fix quotes

---

specification/record-locator/consumer.yaml

NRL-474  update examples for author

---

specification/record-locator/consumer.yaml

update docs to let category filter be in description

---

specification/record-locator/consumer.yaml

NRL-478 update docs for context

---

specification/record-locator/consumer.yaml

[NRL-518] Add validation for content

---

specification/record-locator/consumer.yaml

[NRL-1228] Fix advance care plan naming

---

specification/record-locator/consumer.yaml

NRL-1075 update category multi search 

---

specification/record-locator/consumer.yaml

NRL-477 change regex for doc status

---

proxies/live/apiproxy/policies/AssignMessage.Errors.CatchAllMessage.xml
proxies/sandbox/apiproxy/policies/AssignMessage.Errors.CatchAllMessage.xml

[NRL-1180] Add escapeJSON when returning diagnostics in catch all error handling

---

proxies/live/apiproxy/policies/AssignMessage.Errors.CatchAllMessage.xml
proxies/sandbox/apiproxy/policies/AssignMessage.Errors.CatchAllMessage.xml

[NRL-1180] Fix missing comma in catch-all error handling

---

proxies/live/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/targets/sandbox.xml

[NRL-1322] Set condition to check headers when using AddCors step

---

proxies/sandbox/apiproxy/proxies/default.xml

[NRL-1322] Remove CORS condition block for sandbox proxies

---

Makefile
README.md
proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
proxies/live/apiproxy/policies/AssignMessage.AddCorsPreflight.xml
proxies/live/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
proxies/sandbox/apiproxy/policies/AssignMessage.AddCorsPreflight.xml
proxies/sandbox/apiproxy/proxies/default.xml

NRL-1330 fix cors issue

---

specification/record-locator/consumer.yaml

NRL-505 Modify error documentation

---

specification/record-locator/consumer.yaml

NRL-512 Update documentation for HEAD requests

---

proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
specification/record-locator/consumer.yaml

remove ods code extension header

---

specification/record-locator/consumer.yaml

NRL-1533 Use HTML to avoid pipe rendering issues

---

specification/record-locator/consumer.yaml

NRL-1491 Add InContext retrieval mechanism

---

specification/record-locator/consumer.yaml

NRL-1612 Fix retrieval mechanism url
